version: "3.7"

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documentsdb
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    ports:
      - "54321:5432"
    volumes:
      - documents_db:/var/lib/postgresql/documents_db

volumes:
  documents_db: