version: "3.7"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: kenny_docs_db
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27019:27017
    volumes:
      - kenny_docs_db:/data/db
      
  mongo-express:
    image: mongo-express
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    logging:
      driver: none

volumes:
  kenny_docs_db:
