@host = http://localhost:3000


### Auth

### Register an account
POST {{host}}/auth/register
Content-Type: application/json

{
   "username": "test",
   "password": "test"
}

### Login in an account
POST {{host}}/auth/login
Content-Type: application/json

{
   "username": "test",
   "password": "test"
}


### Admin

### Create a new question
POST {{host}}/admin/question
Content-Type: application/json

{
   "text": "On which continent is Turkey?",
   "answers": [
      "Europe and Asia",
      "Europe",
      "Europe and Africa",
      "Africa"
   ],
   "correctAnswerIndex": 0,
   "domain": "geography"
}

### Update a question
PUT {{host}}/admin/question/12312ewe213
Content-Type: application/json

{
   "text": "On which continent is Turkey?",
   "answers": [
      "Europe and Asia",
      "Europe",
      "Europe and Africa",
      "Africa"
   ],
   "correctAnswerIndex": 0,
   "domain": "geography"
}

### Get some questions
GET {{host}}/admin/question?page=0&size=10&domain=geography
Content-Type: application/json

### Create a new domain
POST {{host}}/admin/domain
Content-Type: application/json

{
   "name": "geography",
   "description": "geography"
}

### Update a domain
PUT {{host}}/admin/domain/60142998be56e48964c87e16
Content-Type: application/json

{
   "name": "geography",
   "description": "The science of the Earth"
}


### Host

### Get domains
GET {{host}}/admin/domain
Content-Type: application/json

### Get random question
GET {{host}}/host/question
Content-Type: application/json
